SENDGRID_USERNAME: myspecialusername
SENDGRID_PASSWORD: exAmplePa$$
MY_SUPER_SECRET_VARIABLE: secret123456
STRIPE_PUBLISHABLE_KEY: pk_test_bWgxlEXzjCrJaYEWXfZKVZod
STRIPE_SECRET_KEY: sk_test_vST0xIwvStdzAcI0sEPTSKWl
